app/views/welcome/index.html.slim
Make range map show on homepage. It's a 10Mb download so this
could be slow ... works fast locally, but likely need tiling
=> GeoJSON version of range map

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/aaed.css.scss, app/assets/stylesheets/application.css.scss, app/controllers/welcome_controller.rb, app/views/layouts/bootstrapped.html.slim, app/views/welcome/index.html.slim
This series of commits makes Bootstrap available to the site, provides some mechanisms for Bootstrap-ifying selected pages, and makes a start of doing that on the new homepage.
=> Bootstrap for homepage

config/deploy.rb
Make sure RVM is updated on each deploy.
=> Update Capistrano deployment recipe

app/assets/stylesheets/aaed.css.scss
See http://guides.rubyonrails.org/asset_pipeline.html
=> Use asset url in CSS

Gemfile
=> Fix Gemfile reference to Ruby version

app/models/country.rb, app/models/species_range_state_country.rb, config/initializers/rails_admin.rb
First steps for Rails Admin, get things showing up properly, and authenticated.
=> Rails admin

config/deploy.rb
This merges the deploy recipe changes from the maintenance branch
and also adds the dev target. I'll make some direct commits if there are issues with the recipe (since it has to be correct in the repo for a deploy to succeed, and I don't want to make infinite PRs about it)
=> Introduce dev deploy recipe

config/environments/production.rb, config/initializers/setup_mail.rb
Port a change from maintenance branch
=> Change mail configuration to use local Postfix

app/assets/stylesheets/aaed.css.scss, app/controllers/population_submissions_controller.rb, app/helpers/application_helper.rb, app/views/devise/registrations/edit.html.slim, app/views/devise/shared/_links.slim, app/views/layouts/application.html.slim, app/views/layouts/survey_display.html.slim, app/views/submissions/_form.html.slim, app/views/submissions/edit.html.slim, app/views/submissions/new.html.slim, app/views/welcome/index.html.slim, config/deploy.rb
Work towards resolving stopper cosmetic and usability issues that would prevent the master branch (on dev) from being promoted to staging/live. Substantial work around forms and submissions remains to bring it to parity.
=> Work in progress: address cosmetic and usability regressions on master

.gitignore, Gemfile, app/controllers/spreadsheets_controller.rb, app/helpers/alt_dpps_helper.rb, app/helpers/spreadsheets_helper.rb, app/views/spreadsheets/index.html.slim, app/views/spreadsheets/show.html.slim, config/routes.rb
Added a means of calculating data statistics using a formula
alternative to the DPPS rules. Also, included a verification
tool at /spreadsheets that can be used to check data values
against expected values.
Note: this branch does NOT make any changes to reports.
=> Calculate statistics based on DPPS alternative.

app/assets/stylesheets/aaed.css.scss, app/views/layouts/count_crud_form.html.slim, app/views/layouts/survey_display.html.slim, app/views/population_submission_attachments/_form.html.slim, app/views/population_submission_attachments/show.html.slim, app/views/population_submissions/show.html.slim, app/views/survey_aerial_sample_count_strata/_form.html.slim, app/views/survey_aerial_sample_count_strata/show.html.slim, app/views/survey_aerial_sample_counts/_form.html.slim, app/views/survey_aerial_total_count_strata/_form.html.slim, app/views/survey_aerial_total_count_strata/show.html.slim, app/views/survey_aerial_total_counts/_form.html.slim, app/views/survey_dung_count_line_transect_strata/_form.html.slim, app/views/survey_dung_count_line_transect_strata/show.html.slim, app/views/survey_faecal_dna_strata/_form.html.slim, app/views/survey_faecal_dna_strata/show.html.slim, app/views/survey_ground_sample_count_strata/_form.html.slim, app/views/survey_ground_sample_count_strata/show.html.slim, app/views/survey_ground_total_count_strata/_form.html.slim, app/views/survey_ground_total_count_strata/show.html.slim, app/views/survey_individual_registrations/_form.html.slim, app/views/survey_individual_registrations/show.html.slim, app/views/survey_others/_form.html.slim, app/views/survey_others/show.html.slim
Use Twitter Bootstrap to enforce a responsive layout on all the data survey forms and show pages.
=> Data survey forms and show pages get a responsive layout

app/assets/stylesheets/aaed.css.scss, app/views/application/_count_info.html.slim, app/views/application/_count_stratum_info.html.slim, app/views/application/_population_submission_info.html.slim, app/views/application/_submission_info.html.slim, app/views/data_request_forms/thanks.html.slim, app/views/layouts/application.html.slim, app/views/population_submissions/submit.html.slim, app/views/submissions/show.html.slim
More tweaks in to utilize Bootstrap, plus a few styling fixes from the conversion to slim.
=> WIP more Bootstrap styling fixes

.gitignore, Gemfile, Gemfile.lock, app/controllers/population_submission_attachments_controller.rb, app/controllers/survey_crud.rb, app/models/population_submission.rb, app/models/population_submission_attachment.rb, app/models/population_submission_geometry.rb, app/views/population_submission_attachments/show.html.slim, config/locales/en.yml, db/migrate/20111011191017_devise_create_users.rb, db/migrate/20151123204038_change_attribute_name.rb, db/schema.rb
- Stores things on local filesystem for simplicity on dev and during practicum
- Extracts ZIPped shapefiles into component parts
- Opens the shapefile and imports its strata to a table of geometries bound to the current population submission
- Updates the database schema and various model elements with new postgis adapter capabilities
=> Shapefile opening, importing with rgeo pipeline

app/controllers/report_controller.rb, app/controllers/spreadsheets_controller.rb, app/helpers/alt_dpps_helper.rb, app/models/sql_reader.rb, app/views/report/_table_alt_dpps.html.slim, db/migrate/20151122032652_generate_view_efacadd.rb, db/migrate/20151123213012_revise_view_efacadd.rb, script/etl/estimate_factors_analyses_categorized_for_add.2.sql, script/etl/estimate_factors_analyses_categorized_for_add.sql
Cosmetic updates for the report pages, and moved the current SQL to a view for easier querying since it needs to be grouped.
=> ADD Views and Cosmetics

app/controllers/survey_crud.rb, app/models/stratum_level_validator.rb
Fixed a couple issues with saving strata:
* Validator had a copy/paste issue that was causing one of the fields to not be validated
* Controller needed to directly call rendering on failed submissions.
=> Strata Saving

app/controllers/population_submission_attachments_controller.rb, app/models/population_submission_attachment.rb, app/models/population_submission_geometry.rb, app/views/application/_population_submission_info.html.slim, app/views/population_submissions/_form.html.slim, app/views/population_submissions/new.html.slim, db/migrate/20151124041257_add_source_and_binding_to_population_submission_geometries.rb, db/schema.rb
Make the import process a bit more manageable
=> GIS import improvements

app/views/about/index.html.slim
Change to use the main CITES url as the link instead of MIKE.
Test #362
=> Update CITES url

app/controllers/spreadsheets_controller.rb, app/views/spreadsheets/index.html.slim, app/views/spreadsheets/show.html.slim, app/views/superuser/index.html.slim, config/routes.rb
Added navigation to and around the spreadsheets, and a means
of deleting existing spreadsheets.  Also, sanity check the
names of the spreadsheets.
=> Spreadsheet page navigation, delete feature.

app/controllers/report_controller.rb, app/helpers/alt_dpps_helper.rb, app/views/report/_table_alt_dpps.html.slim, app/views/report/_table_country_regional_data_quality_add.html.slim, app/views/report/preview_country.html.slim, app/views/report/preview_region.html.slim, db/migrate/20151130171930_create_view_country_range_support.rb, db/migrate/20151130175516_create_view_add_totals.rb, script/etl/country_range_support.sql, script/etl/estimate_factors_analyses_categorized_totals_for_add.sql
More views and tables to display ADD versions of data alongside DPPS versions.
=> Alt dpps data quality

app/controllers/population_submission_attachments_controller.rb
Minor change to support downloads against locally stored files.
=> Fix download file option for local storage

app/controllers/report_controller.rb, app/helpers/alt_dpps_helper.rb, app/models/sql_reader.rb, app/views/application/_tabs.html.slim, app/views/report/_table_alt_dpps.html.slim, app/views/report/_table_continental_regional_data_quality_add.html.slim, app/views/report/_table_country_regional_data_quality_add.html.slim, app/views/report/preview_continent.html.slim, app/views/report/preview_country.html.slim, app/views/report/preview_region.html.slim, db/migrate/20151210171432_add_spatial_queries.rb, script/etl/estimate_factors_analyses_categorized_for_add.3.sql, script/etl/static_spatial_queries_add.sql
All pages where DPPS was used now have alternate ADD calculations available.
=> ADD outliers

app/models/analysis.rb
"changes" is reserved so we mustn't use that word
=> Workaround a production issue

app/controllers/analyses_controller.rb, app/models/analysis.rb, app/views/superuser/index.html.slim
Bugfixes on analysis creation. Last mini-PR for a while I hope. Just want to verify no regressions with this applied.
=> Review support

app/controllers/analyses_controller.rb, app/views/analyses/new.html.slim, db/migrate/20160109011528_create_spatial_indices.rb, db/migrate/20160109011529_test_regenerating_all_static_spatial_queries.rb, db/schema.rb, script/etl/static_spatial_queries.sql
This also incorporates a copy command for basing a new analysis
on an old baseline.
=> Clear up blockers preventing new analysis on DEV

app/helpers/alt_dpps_helper.rb, app/views/report/_table_alt_dpps.html.slim
There are some issues causing Kenya on DEV to crash currently,
after re-creating all the view stacks and migrating to recent
PostGIS. This *workaround* (not a fix) causes ? to be emitted
in place of crashing the page so work can proceed while we look
into this.
=> Workaround an issue with alt_dpps and range

app/assets/javascripts/analyses.coffee, app/assets/stylesheets/analyses.scss, app/controllers/countries_controller.rb, app/helpers/analyses_helper.rb, app/models/change.rb, app/views/analyses/show.html.slim, db/migrate/20160110191217_add_comments_to_changes.rb, db/schema.rb
Moved the JS and CSS where it goes, mostly. Features are being zoomed and highlighted now. Comments moved below the row for more room.
=> More complete and cleaned behavior in the replacement manager

app/controllers/report_controller.rb, app/views/report/preview_country.html.slim
Order of operations not being applied correctly, insert
parentheses to fix issue.
See #408
=> PFS formula correction for certain reports.

app/helpers/alt_dpps_helper.rb, app/views/report/_table_alt_dpps.html.slim, db/migrate/20160112233542_next_gen_add_spatial_queries.rb, script/etl/static_spatial_queries_add.2.sql
=> Fix alt dpps tables

app/views/layouts/application.html.slim, config/deploy.rb, config/unicorn/production.rb
May follow this with some direct commits if there are issues with the deploy recipe to avoid too many PRs.
=> Minor changes: update deployment recipe and remove support from banner

app/controllers/report_controller.rb
Order of operations not being applied correctly, insert
parentheses to fix issue.
See #408
=> PFS formula correction for continental report.

app/views/population_submissions/_form.html.slim, app/views/population_submissions/submit.html.slim, app/views/survey_aerial_sample_count_strata/_form.html.slim, app/views/survey_aerial_total_count_strata/_form.html.slim, app/views/survey_dung_count_line_transect_strata/_form.html.slim, app/views/survey_faecal_dna_strata/_form.html.slim, app/views/survey_ground_sample_count_strata/_form.html.slim, app/views/survey_ground_total_count_strata/_form.html.slim, db/migrate/20160211021325_add_comments_to_strata.rb, db/schema.rb
Generally, two more blocks to follow; just want these cleared off the decks first in case we need to revert anything.
=> Group of trivial commits around SOW3/Review Tooling

app/models/analysis.rb, app/models/population_submission.rb, app/models/submission.rb, app/models/survey_aerial_sample_count.rb, app/models/survey_aerial_total_count.rb, app/models/survey_dung_count_line_transect.rb, app/models/survey_faecal_dna.rb, app/models/survey_ground_sample_count.rb, app/models/survey_ground_total_count.rb, app/views/application/_count_info.html.slim, app/views/application/_count_stratum_info.html.slim, app/views/application/_population_submission_info.html.slim, app/views/application/_submission_info.html.slim
Keep forgetting to commit this -- Tara reminded me today!
=> Cascading deletes

app/views/superuser/index.html.slim
=> Reorder, text changes to /superuser

app/views/superuser/index.html.slim, config/routes.rb, public/404.html
New language on the 404 page. 
New style on the Superuser page.
Commit to update config/routes to remove Maps.
=> New 404, Superuser style

app/controllers/population_submissions_controller.rb, app/controllers/survey_crud.rb, app/views/population_submissions/show.html.slim
Merge this to enable deploying to Staging for Reuben to test
=> Conditionals for single stratum types

public/401.html
Should have been in the previous commit.
=> 401 page for unauthorized access.

app/controllers/continents_controller.rb, app/controllers/countries_controller.rb, app/controllers/regions_controller.rb, app/models/continent.rb, app/models/country.rb, config/routes.rb
little bit of refactor to keep things D.R.Y.
=> add endpoints for country, region, and continent, for #486

db/migrate/20160413154836_populate_centroids.rb
=> Migration to calculate missing centroids

app/controllers/changes_controller.rb, app/controllers/population_submission_attachments_controller.rb, app/models/change.rb, app/views/changes/_form.html.slim, app/views/changes/index.html.slim, db/migrate/20160415022317_add_population_to_changes.rb, db/schema.rb
This should be safe to load to staging (whenever migrations are next run on staging)
=> Add "population" to changes table and views

app/assets/stylesheets/aaed.css.scss, app/helpers/alt_dpps_helper.rb, app/views/report/_table_alt_dpps.html.slim, app/views/report/_table_continental_regional_data_quality.html.slim, app/views/report/_table_continental_regional_data_quality_add.html.slim, app/views/report/_table_country_regional_data_quality.html.slim, app/views/report/_table_country_regional_data_quality_add.html.slim, app/views/report/country.html.slim, app/views/report/preview_country.html.slim, app/views/report/preview_site.html.slim, app/views/report/survey.html.slim
Rearranged the range sections of ADD tables and manually round PFS values.
=> Report formatting

app/views/report/preview_country.html.slim
Remove contents of the PFS column at the strata level from Tables
Test #494
=> Don't show PFS on strata level

app/views/data_request_forms/hold.html.slim, config/routes.rb
=> Move data request forms, add holding message

app/assets/javascripts/analyses.coffee, app/views/analyses/show.html.slim
Headed just for dev, for Virginia to test
=> Replacement manager things

db/migrate/20160419101317_change_dung_count_fields_to_floats.rb, db/schema.rb
=> Dung count migrations headed for dev

db/migrate/20160511181514_increase_change_column_sizes.rb, db/schema.rb, lib/sql_helper.rb, script/calculator/20160511/1000_flush_analyses_view_dependencies.sql, script/calculator/20160511/1100_new_estimates_views.sql
=> Expand column size of new and replaced strata

app/helpers/alt_dpps_helper.rb
Was not taking into account the fact that a single strata
could be replaced by multiple strata; grouped such that
this is supported in calculations.
See #550
=> For ADD IoC, change grouping strategy.

app/helpers/alt_dpps_helper.rb
Modify the query to check for cases where there is no old
comparison data and supply zeroes as defaults (i.e. when
the reason for change is NP).
Also, catch cases where there is no new comparison data yet
by directly querying the changes table, so that new information
that is included in the changes table can be analyzed.
See #550
=> Expand reach of ADD IoC query.

app/controllers/report_controller.rb, app/helpers/alt_dpps_helper.rb, app/views/report/_table_causes_of_change_add.html.slim
=> Display area statistics on ADD IoC table.

app/helpers/dpps_country_helper.rb, app/views/report/preview_country.html.slim
=> Expose populations in tables

app/controllers/report_controller.rb, app/views/report/_table_country_zones_add.html.slim, app/views/report/_table_country_zones_dpps.html.slim
=> Group by population for ADD country zones.

app/models/region.rb
Use the new regional stats queries to get the stats and sums
for each country within a region.
=> Update region queries for ADD.

app/controllers/continents_controller.rb, app/controllers/countries_controller.rb, app/controllers/regions_controller.rb, app/models/continent.rb, app/models/country.rb, app/models/region.rb, config/routes.rb
A few small API updates; should have no impact on the website
=> API updates

app/views/report/_table_causes_of_change.html.slim, app/views/report/_table_causes_of_change_add.html.slim, app/views/report/_table_causes_of_change_dpps.html.slim, config/locales/en.yml
=> Empty table message for IoC report table.

app/controllers/report_controller.rb, app/views/report/_table_alt_dpps.html.slim, app/views/report/preview_continent.html.slim, app/views/report/preview_country.html.slim, app/views/report/preview_region.html.slim
And baseline numbers for ADD summary.
=> Reorder tabs

app/controllers/report_controller.rb, app/views/report/appendix_2.html.slim
And baseline numbers for ADD summary.
=> Regional totals for Appendix II

app/models/continent.rb, app/models/country.rb, app/models/region.rb
was disappointed to see that there is no good denormalized column to join tables like countries + country on, so I'm just using the name columns
=> fix db joins for maps

app/models/region.rb
Use plural form of subgeography name in sums key for ADD data.
=> Update API Keys

.gitignore
add upload directory to gitignore
=> add upload directory to gitignore

docker-compose.yml
update docker db image for parity with dokku
=> update docker db image for parity with dokku

app/assets/stylesheets/aaed.css.scss, app/assets/stylesheets/application.css.scss, app/views/about/index.html.slim, app/views/report/species.html.slim
Update the "Want Data" section on the About and Report sections with a link to the provided Google Form. Added an external indicator to the link for clarity
=> update want data with google form link

README.md
Added section of readme with helpful commands for local Docker env
=> update readme with helpful commands for local docker env
