AfESG/AED-Platform

- .gitignore
- Gemfile
- app/controllers/report_controller.rb
- app/controllers/spreadsheets_controller.rb
- app/helpers/alt_dpps_helper.rb
- app/helpers/spreadsheets_helper.rb
- app/views/report/_table_alt_dpps.html.slim
- app/views/report/preview_region.html.slim
- app/views/spreadsheets/index.html.slim
- app/views/spreadsheets/show.html.slim
- config/routes.rb
This PR achieves the same thing as the previous one, but also includes a commit to display the DPPS summary table alongside the new calculation methods with and without rounding.  This is only available on the 2013 preview report on the region pages, as a proof of concept, but can be scaled to all pages once we finalize it.
You can safely merge the other PR without affecting reports.  Or, you can immediately change the reports by merging this PR.
> DPPS Reporting + Proof of Concept

- app/controllers/report_narratives_controller.rb
- app/models/submission.rb
- app/views/layouts/count_crud_form.html.slim
- app/views/population_submission_attachments/_form.html.slim
- app/views/population_submissions/_form.html.slim
- app/views/report_narratives/new.html.slim
- app/views/submissions/_form.html.slim
- app/views/survey_aerial_sample_count_strata/_form.html.slim
- app/views/survey_aerial_sample_counts/_form.html.slim
- app/views/survey_aerial_total_count_strata/_form.html.slim
- app/views/survey_aerial_total_counts/_form.html.slim
- app/views/survey_dung_count_line_transect_strata/_form.html.slim
- app/views/survey_faecal_dna_strata/_form.html.slim
- app/views/survey_ground_sample_count_strata/_form.html.slim
- app/views/survey_ground_total_count_strata/_form.html.slim
- app/views/survey_individual_registrations/_form.html.slim
- app/views/survey_others/_form.html.slim
Fields that are hidden now have their values set
using the input_html hash instead of being directly
set.  I believe this is a library API change.
See #371
> Correct validation errors for hidden fields.

- app/views/report/preview_country.html.slim
- app/views/report/preview_site.html.slim
Some important data tags must have went missing in
transport.  Restore the proper attributes so things
expand as advertised.
Also, related, fixed an issue in the country/site
reports where an improper assignment operator was
being used.  Old template style, conversions didn't
pick it up.
> Restore javascript toggle of survey zones.

- app/controllers/survey_geometries_controller.rb
- app/helpers/application_helper.rb
- app/views/application/_map_stratum.html.slim
- app/views/survey_aerial_sample_count_strata/show.html.slim
- app/views/survey_aerial_total_count_strata/show.html.slim
- app/views/survey_dung_count_line_transect_strata/show.html.slim
- app/views/survey_faecal_dna_strata/show.html.slim
- app/views/survey_ground_sample_count_strata/show.html.slim
- app/views/survey_ground_total_count_strata/show.html.slim
- app/views/survey_individual_registrations/show.html.slim
- app/views/survey_others/show.html.slim
- config/application.rb
- config/routes.rb
- db/migrate/20151124062712_add_survey_geom.rb
- db/schema.rb
This is built on the rgeo, leaflet, geojson stack and discards the
old Google Maps function with hand-built polygons. Accordingly,
this now correctly previews multipolygons which clears the
longstanding issue #331.
rgeo has trouble with a geometry column named 'geometry' due to a
name conflict; also the existing survey_geometry.geometry column
had a mix of 2d/3d and different SRID data in it. A migration here
creates a new 'geom' column but doesn't do anything to populate or
use it higher in the stack.
For now, a manual query is necessary to migrate old data into this
column:
update survey_geometries set geom=ST_Force2D(geometry);
This will be added to a migration later that is capable of also
updating the rest of the view stack to track this change.
Fix #331
> New viewer for stratum data

- app/helpers/alt_dpps_helper.rb
In ADD calculation, ensure that the modeled extrapolations,
in this case, Rest of Gabon, are not included in the sums,
as they are already accounted for in another category.
See #383
> Remove modeled extrapolations from D calcs.

- db/migrate/20160119002041_recapture_missing_2007_geometries.rb
- db/schema.rb
This is implemented as a migration, but to get a useful result
from the migration, you must first have a copy of an original
AED 2007 shapefile loaded at "julian_2007" -- load the >3Mb
dumpfile or a shapefile directly to obtain this, or just get
a database image that has already had this migration run.
The migration emits a (hopefully) useful log of what it
recaptures.
> 2007 geometry recapture script

- app/assets/javascripts/country-map.coffee
- app/assets/stylesheets/country-map.scss
- app/controllers/countries_controller.rb
- app/controllers/report_controller.rb
- app/models/change.rb
- app/views/application/_tabs.html.slim
- app/views/report/_map.html.slim
- app/views/report/preview_country.html.slim
- config/routes.rb
This shows a version of the Replacement Manager map on a tab in
the Country reports page. This is a largish commit because it
adds two new bits of plumbing: the ability to deferred load a
map on demand (as opposed to when the page is created) and also
some model mechanics for selectively including just those strata
included in a given analysis. These bits of plumbing should
be useful later in providing exports for printed report
generation. The model plumbing could be done with greater
efficiency by leveraging existing PostgreSQL views
if it needs to be accelerated -- with the tradeoff of tightly
binding the code to those views and needing to maintain both
SQL and Ruby code around this feature.
The map tab is only rendered at present for superusers, so this
code can be pushed to …
> Country level mapping

- app/controllers/changes_controller.rb
- app/helpers/changes_helper.rb
- app/views/changes/_form.html.slim
- app/views/changes/edit.html.slim
- app/views/changes/index.html.slim
- app/views/changes/new.html.slim
- app/views/changes/show.html.slim
- app/views/superuser/index.html.slim
- config/routes.rb
The underlying /changes plumbing is depended on by the new replacement manager, so can't strip it out.
> Revert and reintroduce "Disable changes form"

- db/migrate/20160131211655_recapture_s3_files.rb
- db/schema.rb
This migration requires you have a copy of AfESG's S3 data spool in
/u/s3 with each bucket enumerated below. If you don't care about
relinking these files, you can just make a stub directory at /u/s3
to pass this migration.
When a corresponding ID and filename are found in the S3 spool, the
file is reattached and relinked to the PopulationSubmissionAttachment
exactly as if it had been resubmitted. This creates a paper_trail
entry for the change and makes a copy of the file in the appropriate
working directory.
Unless there are exact ID and filename matches in the S3 spool, this
migration should not clobber or evict any other attachements.
Test #455
> Relink survey data files

- db/migrate/20160201001116_recapture_all_2007_geometries.rb
- db/schema.rb
This walks all 2007 geometries and attempts to reload them from
original source -- a fresh pgsql import of the ArcGIS files from
Julian's old computer. The match is done now on
iso_code
completion_year
survey_zone
designate
short_citation
which should eliminate most opportunities to load the wrong
thing. Because it reloads all 2007 geometries, this will also
catch cases where a data manager previously linked the wrong
thing -- in the last attempt, we were leaving those alone.
Geometries which can NOT be matched on those parameters to what
was published in 2007 are unlinked from anything, to avoid the
chance of being linked to the WRONG thing which is confusing
and wrong.
One known spot case where this occurs is Tanzania's 2006
Katavi-Rukwa (Outside).
This commit clears the examples in the …
> Reload all 2007 geometries

- public/404.html
The Tables URL on the 404 page still had /Loxodonta_africana in
the URL. I removed it.
See #465
> Update Tables URL on 404

- app/controllers/application_controller.rb
When a non-admin tries to access a preview report that they
are not supposed to access, throw NotAuthorizedException and
render a page telling them they do not have access to the
content.
See #502
> Block unauth'd access to preview reports.

- Gemfile
- Gemfile.lock
- app/controllers/survey_geometries_controller.rb
- app/views/application/_map_stratum.html.slim
- config/routes.rb
This will download a fairly basic shapefile of any stratum in
the system ... potentially useful for reusing these geometries
in other contexts.
Since RGeo's shapefile export is nonexistent, this reintroduces
GeoRuby.
> Experimental shapefile downloader for superusers

- app/helpers/alt_dpps_helper.rb
- app/models/sql_reader.rb
- db/migrate/20160427225620_efac_add_v4.rb
- db/schema.rb
- script/etl/estimate_factors_analyses_categorized_for_add.4.sql
Updated the view to calculate Degraded Data (now referred to
as Outdated Data) by comparing the analysis_year to the
completion_year (age) instead of hard-coding this.
Also, Other Guesses (category E) no longer calculates the
Estimate column. This is a change in methodology from the
original spec.
Note: there is no "down" method for this migration; it will
just replace the estimate_factors_analyses_categorized_for_add
database view.
See #532
See #539
> Calculation updates for ADD summary.

- app/controllers/report_controller.rb
- app/helpers/alt_dpps_helper.rb
- app/views/report/_table_alt_dpps.html.slim
- db/migrate/20160516152207_add_change_interpreters.rb
- db/schema.rb
- script/calculator/20160516/1000_flush_analyses_view_dependencies.sql
- script/calculator/20160516/1100_new_estimates_views.sql
- script/calculator/20160516/1110_estimate_factors_analyses_categorized_for_add.sql
- script/calculator/20160516/1200_static_spatial_queries.sql
- script/calculator/20160516/1210_static_spatial_range_queries.sql
- script/calculator/20160516/1220_static_spatial_area_of_range.sql
- script/calculator/20160516/2000_new_change_interpreters.sql
- script/calculator/20160516/2100_country_change_interpreters.sql
- script/calculator/20160516/2200_regional_change_interpreters.sql
- script/calculator/20160516/2300_continental_change_interpreters.sql
- script/calculator/20160516/2400_materialize_dpps_change_interpreters.sql
- script/calculator/20160516/2500_country_change_interpreters_add.sql
- script/calculator/20160516/3100_country_range_support.sql
Reintroduced the spatial range and area queries to the
calculator and added means of regenerating the surveys
table. Also, changed the generation logic for the IoC
ADD table to be more consistent with that of DPPS, for
comparative reasons.
Also, removed report-based mentions of 2013_africa_final
in favor of joining to the analyses table and filtering
based on the request. Changed views and queries to support
this where appropriate.
Finally, updated a couple sum counts along the way for ADD
and added a better correction for area-rendering issues in
the main statistical table.
See #550
> Analysis-centric reports, IoC stats, recalc.

- app/controllers/welcome_controller.rb
- app/helpers/alt_dpps_helper.rb
- app/helpers/report_helper.rb
- app/views/report/_table_causes_of_change_add.html.slim
- db/migrate/20160517151710_recreate_cause_of_changes_table.rb
- db/migrate/20160518220547_correct_add_change_interpreters.rb
- script/calculator/20160518/1000_flush_analyses_view_dependencies.sql
- script/calculator/20160518/1100_new_estimates_views.sql
- script/calculator/20160518/1110_estimate_factors_analyses_categorized_for_add.sql
- script/calculator/20160518/1200_static_spatial_queries.sql
- script/calculator/20160518/1210_static_spatial_range_queries.sql
- script/calculator/20160518/1220_static_spatial_area_of_range.sql
- script/calculator/20160518/2000_new_change_interpreters.sql
- script/calculator/20160518/2100_country_change_interpreters.sql
- script/calculator/20160518/2200_regional_change_interpreters.sql
- script/calculator/20160518/2300_continental_change_interpreters.sql
- script/calculator/20160518/2400_materialize_dpps_change_interpreters.sql
- script/calculator/20160518/2500_country_change_interpreters_add.sql
- script/calculator/20160518/3100_country_range_support.sql
- script/etl/update_causes_of_change_table.sql
Updated the logic behind the cause of change queries to
provide more accurate numbers across the board, as well
as more accurate totals, particular for CL.
Also, made static tables from views to make queries faster,
and added these to the /recalc command.
Finally, changed the confidence column to always be positive
based on the sum of the variance instead of the difference,
and adjusted the report display accordingly.
See #550
See #557
> More accurate cause of change numbers, totals.

- app/controllers/report_controller.rb
- app/helpers/alt_dpps_helper.rb
- app/models/sql_reader.rb
- app/views/report/appendix_2.html.slim
- db/migrate/20160531062918_dung_count_guesses.rb
- db/schema.rb
- script/calculator/20160531/1000_flush_analyses_view_dependencies.sql
- script/calculator/20160531/1100_new_estimates_views.sql
- script/calculator/20160531/1110_estimate_factors_analyses_categorized_for_add.sql
- script/calculator/20160531/1200_static_spatial_queries.sql
- script/calculator/20160531/1210_static_spatial_range_queries.sql
- script/calculator/20160531/1220_static_spatial_area_of_range.sql
- script/calculator/20160531/2000_new_change_interpreters.sql
- script/calculator/20160531/2100_country_change_interpreters.sql
- script/calculator/20160531/2200_regional_change_interpreters.sql
- script/calculator/20160531/2300_continental_change_interpreters.sql
- script/calculator/20160531/2400_materialize_dpps_change_interpreters.sql
- script/calculator/20160531/2500_add_change_interpreters.sql
- script/calculator/20160531/2600_country_change_interpreters_add.sql
- script/calculator/20160531/2700_regional_change_interpreters_add.sql
- script/calculator/20160531/2800_continental_change_interpreters_add.sql
- script/calculator/20160531/3100_country_range_support.sql
- script/calculator/20160531/4000_input_zone_exporter_view.sql
- script/calculator/20160531/5000_appendix_2.sql
For category C, the guess max calculation now incorporates
the confidence level, and also uses the given min/max values
instead of the estimate value, when available. This change
required a bit of a ground-up change in the way ADD values are
stored, calculated, and queried.
New calculator includes changes to the main ADD estimate table
to include appropriate column information, summary and totals
tables for each hierarchical level (country, region, continent)
and a revamp of the cause of changes tables to properly incorporate
the new guesses column.
The queries in the ADD helper class has been updated to use the
new tables, and moved the country stats query to the helper
class.
Important to note is that estimates_...reasons_for_add is gone,
which directly affects the new Appendix II …
> Changed calculation method for other dung count.

- app/controllers/report_controller.rb
- app/views/report/appendix_1.html.slim
- app/views/report/general_statistics.html.slim
- db/migrate/20160604225027_general_statistics_support.rb
- db/schema.rb
- script/calculator/20160604/1000_flush_analyses_view_dependencies.sql
- script/calculator/20160604/1100_new_estimates_views.sql
- script/calculator/20160604/1110_estimate_factors_analyses_categorized_for_add.sql
- script/calculator/20160604/1200_static_spatial_queries.sql
- script/calculator/20160604/1210_static_spatial_range_queries.sql
- script/calculator/20160604/1220_static_spatial_area_of_range.sql
- script/calculator/20160604/1230_static_spatial_general_statistics.sql
- script/calculator/20160604/2000_new_change_interpreters.sql
- script/calculator/20160604/2100_country_change_interpreters.sql
- script/calculator/20160604/2200_regional_change_interpreters.sql
- script/calculator/20160604/2300_continental_change_interpreters.sql
- script/calculator/20160604/2400_materialize_dpps_change_interpreters.sql
- script/calculator/20160604/2500_add_change_interpreters.sql
- script/calculator/20160604/2600_country_change_interpreters_add.sql
- script/calculator/20160604/2700_regional_change_interpreters_add.sql
- script/calculator/20160604/2800_continental_change_interpreters_add.sql
- script/calculator/20160604/3100_country_range_support.sql
- script/calculator/20160604/4000_input_zone_exporter_view.sql
- script/calculator/20160604/5000_appendix_2.sql
- script/etl/safe_isect.sql
New approach. Note that the PL/PGSQL safe_isect command must be
added (stored in script/etl for reference) manually to the db.
This is necessary to deal selectively with some range/PA
intersection geometries that cause self-intersection errors.
See #543
> General statistics support

- app/controllers/report_controller.rb
- app/helpers/alt_dpps_helper.rb
- app/views/report/_table_country_regional_data_quality_add.html.slim
- app/views/report/_table_country_zones_add.html.slim
- db/migrate/20160606070742_add_input_zone_sums.rb
- db/schema.rb
- script/calculator/20160606/1000_flush_analyses_view_dependencies.sql
- script/calculator/20160606/1100_new_estimates_views.sql
- script/calculator/20160606/1110_estimate_factors_analyses_categorized_for_add.sql
- script/calculator/20160606/1120_estimate_locator_for_add.sql
- script/calculator/20160606/1200_static_spatial_queries.sql
- script/calculator/20160606/1210_static_spatial_range_queries.sql
- script/calculator/20160606/1220_static_spatial_area_of_range.sql
- script/calculator/20160606/1230_static_spatial_general_statistics.sql
- script/calculator/20160606/2000_new_change_interpreters.sql
- script/calculator/20160606/2100_country_change_interpreters.sql
- script/calculator/20160606/2200_regional_change_interpreters.sql
- script/calculator/20160606/2300_continental_change_interpreters.sql
- script/calculator/20160606/2400_materialize_dpps_change_interpreters.sql
- script/calculator/20160606/2500_add_change_interpreters.sql
- script/calculator/20160606/2600_country_change_interpreters_add.sql
- script/calculator/20160606/2700_regional_change_interpreters_add.sql
- script/calculator/20160606/2800_continental_change_interpreters_add.sql
- script/calculator/20160606/3100_country_range_support.sql
- script/calculator/20160606/4000_input_zone_exporter_view.sql
- script/calculator/20160606/5000_appendix_2.sql
Added a new calculator that includes a zones view for querying
country statistical information for each input zone, and ensure
proper ADD numbers are being used for guesses and confidence.
Also, update the report to use the ADD numbers appropriately.
Finally, split out the ADD geometry table into its own view so
that the ADD views can be replaced via a single query file
without needing to rebuild the calculator entirely.
> Correct ADD totals calculations, country zones.

- config/initializers/leaflet.rb
This is a different tile source than the MapQuest tiles previously
used by default. If we want MapQuest back, we can get an API key
for it.
> Change default tile URL to OpenStreetMap

- db/migrate/20160722171715_change_interpreter.rb
- db/schema.rb
- script/calculator/20160722/1000_flush_analyses_view_dependencies.sql
- script/calculator/20160722/1100_new_estimates_views.sql
- script/calculator/20160722/1105_estimate_locators.sql
- script/calculator/20160722/1110_estimate_factors_analyses_categorized_for_add.sql
- script/calculator/20160722/1120_estimate_locator_for_add.sql
- script/calculator/20160722/1200_static_spatial_queries.sql
- script/calculator/20160722/1210_static_spatial_range_queries.sql
- script/calculator/20160722/1220_static_spatial_area_of_range.sql
- script/calculator/20160722/1230_static_spatial_general_statistics.sql
- script/calculator/20160722/2000_new_change_interpreters.sql
- script/calculator/20160722/2100_country_change_interpreters.sql
- script/calculator/20160722/2200_regional_change_interpreters.sql
- script/calculator/20160722/2300_continental_change_interpreters.sql
- script/calculator/20160722/2400_materialize_dpps_change_interpreters.sql
- script/calculator/20160722/2500_clean_add_change_interpreters.sql
- script/calculator/20160722/2510_create_add_change_interpreters_base_queries.sql
- script/calculator/20160722/2600_country_change_interpreters_add.sql
- script/calculator/20160722/2700_regional_change_interpreters_add.sql
- script/calculator/20160722/2800_continental_change_interpreters_add.sql
- script/calculator/20160722/3100_country_range_support.sql
- script/calculator/20160722/4000_input_zone_exporter_view.sql
- script/calculator/20160722/4100_input_zone_add_view.sql
- script/calculator/20160722/5000_appendix_2.sql
When auto-adjusting the reason change for the change interpreter,
adjust to DD only if the previous reason change was not already
DD; otherwise, mark it as NC.
Partial migration included here to add a new calculator; run
recalc to update the change interpreter tables.
> Change auto-adjust logic for change interpreter
